### ISSUE TITLE
List PRs by current assignee, not owner

### ISSUE THREAD

**Issue by robcresswell** [Shesekino/bleach#21]
Not sure if this is a config option or something but anyways; Assignee is trivial to change in the UI, and represents the person who is currently working on the PR; the owner requires CLI work to my knowledge.

**Comment by Shesekino** [comment]
that's a great idea, I could introduce it as a flag.
my issue with that idea is that assignees are not often used, leaving this field empty. (the other case, where it's populated by multiple people, can cause the same problem)
this could create a lack of ownership, so I would still like the default owner of "handling" the PR to be its owner.

**Comment by robcresswell** [comment]
How about, when the flag is used, `Assignee` if not null, otherwise `Owner`?

**Comment by Shesekino** [comment]
💯 brilliant

**Comment by joshje** [comment]
I’m also wondering about displaying the list of reviewers as it may be helpful when wondering who to chat to about getting the PR merged. Just a thought.

**Comment by Shesekino** [comment]
this is also a wonderful idea.
I'm trying to keep things minimal, because:
1. I'm lazy
2. we're already linking to the PR ; at this point I would expect its owner to click on the link and take it from there. as I see it, the problem this tool is solving is having to be mindful of all these things. but once someone gets poked, they should be able to continue with the heavy lifting :)

picking who the owner is, is the 80%. giving that owner extra data is the 20%.
what do you think?

**Comment by joshje** [comment]
I agree that fixing the "owner" (preferring assignee) would be the most valuable thing. Shall I work up a PR? Happy for this to be the new default, or should we make this configurable?

**Comment by Shesekino** [comment]
I would prefer for this to be configurable, but the area dealing with configuration has outlived its current usefulness and I would like to make some changes there so we can accommodate all sorts of other features.
so feel free to have it as the new default, and when I get to making this refactor I might break this behaviour (but let you know before installing the new pip package so it hopefully doesn't break anyone's usage)

**Comment by joshje** [comment]
@robcresswell we now have this merged! https://github.com/Shesekino/bleach/pull/22

**Comment by robcresswell** [comment]
Awesome, thanks @Shesekino @joshje
